# Generated by Django 4.2.6 on 2023-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_profile_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
